packages:
  - ./
  - playground
  - docs
  - examples/*
  - test/fixtures/*

shamefullyHoist: true

overrides:
  "@nuxt/content": workspace:*
  "@unhead/vue": ^3.1.8
  unhead: ^3.1.8

allowBuilds:
  "@parcel/watcher": true
  "@tailwindcss/oxide": true
  better-sqlite3: true
  esbuild: true
  sharp: true
  sqlite3: true
  unrs-resolver: true
  vue-demi: true
  workerd: true

minimumReleaseAgeExclude:
  - "@nuxtjs/mdc@0.22.1"
  - remark-mdc@3.11.1
  - miniflare@5.20260825.0-alpha || 5.20260826.0-alpha
  - wrangler@4.126.0 || 4.127.0
  - '@types/node@26.4.0'
  - happy-dom@20.11.9
